site_name: Examen Unidad 6 - Documentaci贸n
nav:
  - Inicio: index.md
  - Gu铆a de Instalaci贸n Windows 11: instalacion_windows11.md
  - Especificaciones T茅cnicas iPhone 16: especificaciones_iphone16.md
  -  Descarga de la documentaci贸n en PDF:
      -  Manual de Instalaci贸n (PDF): Manual_de_Instalacion.pdf
      -  Especificaciones iPhone 16 (PDF): Especificaciones_iPhone16.pdf
theme:
  name: 'readthedocs'
